#!/usr/bin/env bash
# This script is displaying something
while IFS=: read -r USERNAME PASSWORD UID GID COMMENT HOME SHELL; do
echo "The user $USERNAME is part of the $GID gang, lives in $HOME and rides $SHELL. $UID's place is protected by the passcode $PASSWORD, more info about the user here: USER ID INFO" < /etc/passwd
