#!/usr/bin/env bash
# This script is displaying something
while IFS=: read -r USERNAME PASSWORD USERID GID COMMENT HOME SHELL; do
    echo "The user $USERNAME is part of the $GID gang, lives in $HOME and rides $SHELL. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $COMMENT"
done < /etc/passwd
