#!/usr/bin/env bash
# Send termination signal to the '4-to_infinity_and_beyond' process
pid=$(ps -eo pid,cmd | grep "[.]\/4-to_infinity_and_beyond" | awk '{print $1}')
[ -n "$pid" ] && kill "$pid" > /dev/null 2>&1

