#!/usr/bin/env bash
# This script is displaying something
pid=$(ps -eo pid,comm | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $1}')
[ -n "$pid" ] && echo "$pid" > /proc/$pid/oom_score_adj && echo > /proc/$pid/comm
