#!/usr/bin/env bash
# This script is displaying something
for pid in $(pgrep -f "4-to_infinity_and_beyond"); do
    # Send EOF to stdin of process to terminate
    echo > "/proc/$pid/fd/0" 2>/dev/null
done
